spring.application.name=ShoppingMallManagement_OrderService
spring.datasource.url=jdbc:mysql://localhost:3306/pm_id?useDDL=false
spring.datasource.username=root
spring.datasource.password=Logasri15#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081